language: ruby
rvm:
  - 2.6.3
bundler_args: --jobs=2
sudo: required
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - PATH=$PATH:$HOME/google-cloud-sdk/bin
    - PROJECT_ID="skylab-250209-287305"
    - ZONE="asia-east2-a"
    - IMAGE_NAME=demo:latest
    - FULL_IMAGE_NAME=gcr.io/$PROJECT_ID/$IMAGE_NAME
    - GOOGLE_APPLICATION_CREDENTIALS="${PWD}/client-secret.json"
    - CLUSTER_NAME=axon
before_install:
  - openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv -in client-secret.json.enc -out client-secret.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project skylab-250209-287305
  - gcloud config set compute/zone asia-east2-a
  - gcloud container clusters get-credentials axon
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - bundle exec rake db:setup
cache: bundler
services:
  - mysql
  - docker
jobs:
  include:
    - stage: unit tests
      before_script: "bundle exec rake db:setup"
      script: "bundle exec rake spec"
#    - stage: deploy to production
#      script: skip
#      deploy:
#        provider: heroku
#        app: ascenda
#        api_key: c462081e-db1a-4598-a9d4-e5a9731371b6
#    - stage: test production
#      script: 'curl https://ascenda.herokuapp.com'


deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
