services:
  - mysql
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: ruby
rvm:
  - 2.6.3
cache:
  - directories:
    - "$HOME/google-cloud-sdk/"
    - /home/travis/.rvm/
    - bundler: true
before_install:
  - openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv -in client-secret.json.enc -out client-secret.json -d
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud auth activate-service-account --key-file client-secret.json
  - gcloud components install kubectl
  - gcloud config set project skylab-250209-287305
  - gcloud config set compute/zone asia-east2-a
  - gcloud container clusters get-credentials axon
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
bundler_args: --jobs=2
jobs:
  include:
    - stage: unit tests
      before_script: "bundle exec rake db:setup"
      script: "bundle exec rake spec"

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
