language: ruby
rvm:
  - 2.6.3
bundler_args: --jobs=2
sudo: required
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
script:
  - bundle exec rake db:setup
cache: bundler
services:
  - mysql
  - docker
jobs:
  include:
    - stage: unit tests
      before_script: "bundle exec rake db:setup"
      script: "bundle exec rake spec"
#    - stage: deploy to production
#      script: skip
#      deploy:
#        provider: heroku
#        app: ascenda
#        api_key: c462081e-db1a-4598-a9d4-e5a9731371b6
#    - stage: test production
#      script: 'curl https://ascenda.herokuapp.com'

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project skilful-berm-214822
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
