name: ENV_SECRET_03
run-name: ENV_SECRET_03
on:
  push:
    branches:
    - main
    - '*'

jobs:
  Deploy-to-Heroku:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - run: |
        echo "ENV_SECRET_03: ${ENV_SECRET_03}"
        echo "REPO_SECRET: ${REPO_SECRET}"
      env:
        ENV_SECRET_03: ${{ secrets.ENV_SECRET_03 }}
        REPO_SECRET: ${{ secrets.REPO_SECRET }}
