name: Deploy to Heroku PRODUCTION
run-name: Deploy to Heroku PRODUCTION
on:
  push:
    branches:
    - test-merge


jobs:
  Deploy-to-Heroku-PRODUCTION:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
    - name: Call monitoring server to store changelog lines and deploy notes
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: . .github/scripts/merge_pr_script.sh
      env:
        pr_number: ${{ steps.findPr.outputs.pr }}
        pr_body: ${{ steps.findPr.outputs.body }}
        pr_title: ${{ steps.findPr.outputs.title }}
        pr_author: ${{ github.triggering_actor }}
        MONITORING_SERVER_URL: ${{ secrets.MONITORING_SERVER_URL }}
