name: Merge code to staging
run-name: Merge code to staging
on:
  pull_request:
    types:
    - closed
    branches:
    - staging # targeted branch test3
    - test
jobs:
  merge-code-to-staging:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
    - name: Call monitoring server to store changelog lines and deploy notes
      if: github.event.pull_request.merged == true
      run: . .github/scripts/merge_pr_script.sh
      env:
        pr_number: ${{ steps.findPr.outputs.pr }}
        pr_body: ${{ steps.findPr.outputs.body }}
        pr_title: ${{ steps.findPr.outputs.title }}
        pr_author: ${{ github.triggering_actor }}
        MONITORING_SERVER_URL: ${{ secrets.MONITORING_SERVER_URL }}
